apiVersion: v1
kind: Pod
metadata: 
  labels:
    test: liveness-http
  name: liveness-http
spec:
  containers:
  - name: liveness-http
    image: k8s.gcr.io/liveness # golang http server that starts failing after 10 secs. Code at bottom of file.
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: 'Some super awesome value'
      initialDelaySeconds: 3
      periodSeconds: 3



# http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
#     duration := time.Now().Sub(started)
#     if duration.Seconds() > 10 {
#         w.WriteHeader(500)
#         w.Write([]byte(fmt.Sprintf("error: %v", duration.Seconds())))
#     } else {
#         w.WriteHeader(200)
#         w.Write([]byte("ok"))
#     }
# })