apiVersion: v1
kind: Pod
metadata: 
  labels:
    test: liveness-http
  name: liveness-http
spec:
  containers:
  - name: liveness-http
    image: k8s.gcr.io/liveness # golang http server that starts failing after 10 secs. Code at bottom of file.
    args:
    - /server
    ports:
    - name: liveness-port
      containerPort: 8080
      hostPort: 8080

    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: 'Some super awesome value'
      initialDelaySeconds: 3
      periodSeconds: 3

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5